[Adoption] Default physics constants
luanti-org/luanti pull request #14859
Opened 2024-07-16 12:31 UTC by Emojigit

This PR is an adoption of #14828. This PR adds a `minetest.DEFAULT_PHYSICS` table so mods know the default values. The table is compatible with `set_physics_override()`.

## To do

This PR is Ready for Review.

## How to test

Run the unit test `test_player_default_physics` in devtest.

2024-07-16 13:28 UTC, Zughy commented
My whole point is to allow mods to modify the value. Without, it's pretty useless for me

2024-07-16 23:53 UTC, Emojigit commented
> My whole point is to allow mods to modify the value. Without, it's pretty useless for me

Done in 917345d7e. But I wonder if the following code is guaranteed to run before any mods:

https://github.com/minetest/minetest/blob/917345d7e4e6634426a661ac7a4844768dc50fd3/builtin/game/default_physics.lua#L27-L29

2024-07-17 07:34 UTC, Zughy commented
Wait, the change was already possibile without these commits. What I needed was simply a way to do `minetest.DEFAULT_PHYSICS.foo = bar`

2024-07-17 08:10 UTC, Emojigit commented
> Wait, the change was already possibile without these commits

Yeah, only the last commit is meaningful. I kept the previous commits only because I am too lazy to delete them.

2025-01-03 18:21 UTC, Zughy commented
@Emojigit rebase needed

2025-01-30 02:05 UTC, Emojigit commented
I have no idea how to fix whitespaces....

2025-06-15 06:54 UTC, sfence commented
@Emojigit 
It looks like you have incorrect indents in the file `builtin/game/default_physics.lua`. Tabs should be used, no spaces.

2025-06-15 06:57 UTC, sfence commented on doc/lua_api.md
> +    * `minetest.DEFAULT_PHYSICS` contains the default values.
core.DEFAULT_PHYSICS

2025-06-15 06:58 UTC, sfence commented on games/devtest/mods/unittests/player.lua
> +minetest.DEFAULT_PHYSICS.speed = 2 -- Slightly change
Also here, use `core.` instead of `minetest.`

2025-06-15 07:50 UTC, sfence requested changes

2025-06-15 07:50 UTC, sfence commented on games/devtest/mods/unittests/player.lua
> +	minetest.DEFAULT_PHYSICS.speed = 1
core also here

2025-06-15 14:59 UTC, Emojigit commented on games/devtest/mods/unittests/player.lua
> +	minetest.DEFAULT_PHYSICS.speed = 1
oops. Working on it...

2025-06-16 05:21 UTC, sfence commented on games/devtest/mods/unittests/player.lua
> +unittests.register("test_player_default_physics", run_player_default_physics_tests, {player=true})
I do not think it is a good idea to change `core.DEFAULT_PHYSICS` in the Lua function, which is not called during loading time.
Perhaps you could use a small offset value like 1.015625 instead of 2, and keep the original default unchanged?

2025-07-21 22:07 UTC, closed without merging